[package]
name = "tui-color-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
palette = "0.7.6"
regex = "1.12.2"
once_cell = "1"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }

[lib]
name = "tui_color_picker"
path = "src/lib.rs"
